new init script

diff --git a/debian/node-restore.init b/debian/node-restore.init
--- a/debian/node-restore.init
+++ b/debian/node-restore.init
@@ -1,175 +1,240 @@
-#!/bin/sh
+#! /bin/bash
 
-. /lib/lsb/init-functions
-
-NODE_ENV="production"
-PORT="8020"
-APP_DIR="/usr/lib/nodejs/restore"
-NODE_APP="server.js"
-CONFIG_DIR="$APP_DIR"
-PID_DIR="/var/run"
-PID_FILE="$PID_DIR/node-restore.pid"
-LOG_DIR="/var/log"
-LOG_FILE="$LOG_DIR/node-restore.log"
-NODE_EXEC=$(which nodejs)
-
-###############
-
-# REDHAT chkconfig header
-
-# chkconfig: - 58 74
-# description: node-app is the script for starting a node app on boot.
 ### BEGIN INIT INFO
-# Provides: node
-# Required-Start:    $network $remote_fs $local_fs
-# Required-Stop:     $network $remote_fs $local_fs
+# Provides:          node-restore
+# Required-Start:    $remote_fs $named $syslog
+# Required-Stop:     $remote_fs $named $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: start and stop node
-# Description: Node process for app
+# Short-Description: node.js remoteStorage server for Unhosted apps
+# Description:       node.js remoteStorage server for Unhosted apps
 ### END INIT INFO
 
-###############
+# Author: Markus Sabadello <markus@danubetech.com>
+#
 
-USAGE="Usage: $0 {start|stop|restart|status} [--force]"
-FORCE_OP=false
+PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin # modify if you need
 
-pid_file_exists() {
-    [ -f "$PID_FILE" ]
+VAR_LOGS_DIR=/var/log/node-restore
+VAR_LOGS=$VAR_LOGS_DIR/node-restore.log
+
+VAR_RUN=/var/run/node-restore               # in case the init script is run by non-root user, you need to
+                                            # indicate a directory writeable by $NODEUSER to store the PID file
+                                            # NB : 1) /usr/local/var/run does not exist by DEFAULT. Either create it
+                                            #      or choose one of your own liking.
+                                            #      2) node, npm,... are best NOT installed/run as ROOT.
+                                            #         (see here: https://github.com/isaacs/npm/blob/master/README.md)
+
+DESC="node.js remoteStorage server"         # whatever fancy description you like
+
+NODEUSER=node-restore:node-restore          # USER who OWNS the daemon process (no matter whoever runs the init script)
+                                            # user:group (if no group is specified, the primary GID for that user is used)
+
+APP_DIR="/usr/lib/nodejs/restore"
+DAEMON_ARGS="$APP_DIR/server.js"            # path to your node.js server/app
+                                            # NB: don't use ~/ in path
+
+PORT="8020"
+NODE_ENV="production"
+NODE_CONFIG_DIR="$APP_DIR"
+
+NAME=nodejs                                 # name of the node.js executable
+DAEMON=$(which nodejs)                      # this SHOULD POINT TO where your node executable is
+NODECMD="PORT="$PORT" NODE_ENV="$NODE_ENV" NODE_CONFIG_DIR="$NODE_CONFIG_DIR" exec $DAEMON $DAEMON_ARGS >>$VAR_LOGS 2>&1" # node command
+
+# ------------------------------------------------------------------------------ 
+
+[ ! -d "$VAR_LOGS_DIR" ] || { mkdir "$VAR_LOGS_DIR" -p; }
+
+# Do NOT "set -e"
+
+[ $UID -eq "0" ] && VAR_RUN=/var/run # in case this script is run by root, override user setting
+THIS_ARG=$0
+INIT_SCRIPT_NAME=`basename $THIS_ARG`
+[ -h $THIS_ARG ] && INIT_SCRIPT_NAME=`basename $(readlink $THIS_ARG)` # in case of symlink
+INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}                            
+PIDFILE="$VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"
+SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] ||  { echo "can't find Node.js ($DAEMON)"  >&2; exit 0; }
+
+# Exit if the 'run' folder is not present
+[ -d "$VAR_RUN" ] || { echo "Directory $VAR_RUN does not exist. Modify the '$INIT_SCRIPT_NAME_NOEXT' init.d script ($THIS_ARG) accordingly" >&2; exit 0; }
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$INIT_SCRIPT_NAME ] && . /etc/default/$INIT_SCRIPT_NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+# uncomment to override system setting
+VERBOSE=yes
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null \
+		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  Daemon already running $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 1; }
+	start-stop-daemon --start --chuid $NODEUSER --make-pidfile --pidfile $PIDFILE --background --exec  $DAEMON  --startas /bin/sh -- -c "$NODECMD" \
+		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  could not be start $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 2; }
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+	[ "$VERBOSE" != no ] && log_daemon_msg  "  --->  started $DESC" "$INIT_SCRIPT_NAME_NOEXT"
 }
 
-get_pid() {
-    echo "$(cat "$PID_FILE")"
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON
+	RETVAL="$?"
+	#[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/3/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON -- $DAEMON_ARGS
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+  [ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg "  --->  $DESC not running" "$INIT_SCRIPT_NAME_NOEXT"
+  [ "$VERBOSE" != no -a "$RETVAL" = 0 ] && log_daemon_msg "  --->  $DESC stopped" "$INIT_SCRIPT_NAME_NOEXT"
+	return "$RETVAL"
 }
 
-is_running() {
-    PID=$(get_pid)
-    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE  --chuid $NODEUSER --name $NAME
+	return 0
 }
 
-start_it() {
-    mkdir -p "$PID_DIR"
-    mkdir -p "$LOG_DIR"
+#
+# Function that returns the daemon 
+#
+do_status() {
+  #
+  # http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+  # 0 program is running or service is OK
+  # 1 program is dead and /var/run pid file exists
+  # (2 program is dead and /var/lock lock file exists) (not used here)
+  # 3 program is not running
+  # 4 program or service status is unknown
+  RUNNING=$(running)
+  
+  # $PIDFILE corresponds to a live $NAME process
+  ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
+  ISPIDACTIVE=$?
 
-    echo "Starting node-restore ..."
-    PORT="$PORT" NODE_ENV="$NODE_ENV" NODE_CONFIG_DIR="$CONFIG_DIR" $NODE_EXEC "$APP_DIR/$NODE_APP"  1>"$LOG_FILE" 2>&1 &
-    echo $! > "$PID_FILE"
-    echo "node-restore started with pid $!"
-}
-
-stop_process() {
-    PID=$(get_pid)
-    echo "Killing process $PID"
-    kill $PID
-}
-
-remove_pid_file() {
-    echo "Removing pid file"
-    rm -f "$PID_FILE"
-}
-
-start_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "Node app already running with pid $PID"
-            exit 1
-        else
-            echo "Node app stopped, but pid file exists"
-            if [ $FORCE_OP = true ]
-            then
-                echo "Forcing start anyways"
-                remove_pid_file
-                start_it
-            fi
-        fi
-    else
-        start_it
+  if [ -n "$RUNNING" ]; then
+    if [ $ISPIDACTIVE ]; then 
+      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
+      exit 0      
     fi
-}
-
-stop_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            echo "Stopping node app ..."
-            stop_process
-            remove_pid_file
-            echo "Node app stopped"
-        else
-            echo "Node app already stopped, but pid file exists"
-            if [ $FORCE_OP = true ]
-            then
-                echo "Forcing stop anyways ..."
-                remove_pid_file
-                echo "Node app stopped"
-            else
-                exit 1
-            fi
-        fi
+  else
+    if [ -f $PIDFILE ]; then
+      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
+      exit 1
     else
-        echo "Node app already stopped, pid file does not exist"
-        exit 1
+      log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
+      exit 3
     fi
+  fi
+  
 }
 
-status_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "Node app running with pid $PID"
-        else
-            echo "Node app stopped, but pid file exists"
-        fi
-    else
-        echo "Node app stopped"
-    fi
+running() {
+  RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
+  if [ "$?" = 1 ]; then
+    echo y
+  fi
+  
 }
 
-case "$2" in
-    --force)
-        FORCE_OP=true
-    ;;
-
-    "")
-    ;;
-
-    *)
-        echo $USAGE
-        exit 1
-    ;;
-esac
 
 case "$1" in
-    start)
-        start_app
-    ;;
-
-    stop)
-        stop_app
-    ;;
-
-    restart)
-        stop_app
-        start_app
-    ;;
-
-    force-reload)
-        stop_app
-        start_app
-    ;;
-
-    status)
-        status_app
-    ;;
-
-    *)
-        echo $USAGE
-        exit 1
-    ;;
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  status)
+    do_status
+  ;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
+
+exit 0
